/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BibliotecaView;


/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jDEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMLector = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMLibro = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMEjemplar = new javax.swing.JMenuItem();
        jMPrestamo = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        jMenu3.setText("jMenu3");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDEscritorioLayout = new javax.swing.GroupLayout(jDEscritorio);
        jDEscritorio.setLayout(jDEscritorioLayout);
        jDEscritorioLayout.setHorizontalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDEscritorioLayout.setVerticalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        jMenu1.setText("Socios");

        jMLector.setText("Lector");
        jMLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLectorActionPerformed(evt);
            }
        });
        jMenu1.add(jMLector);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Libros");

        jMLibro.setText("Libro");
        jMLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLibroActionPerformed(evt);
            }
        });
        jMenu2.add(jMLibro);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Consultas");

        jMEjemplar.setText("Ejemplar");
        jMEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEjemplarActionPerformed(evt);
            }
        });
        jMenu4.add(jMEjemplar);

        jMPrestamo.setText("Prestamo");
        jMPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPrestamoActionPerformed(evt);
            }
        });
        jMenu4.add(jMPrestamo);

        jMenuBar1.add(jMenu4);

        jMenu8.setText("Salir");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Salir");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEjemplarActionPerformed
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        EjemplarView ev = new EjemplarView();
        ev.setVisible(true);
        jDEscritorio.add(ev);
        jDEscritorio.moveToFront(ev);
    }//GEN-LAST:event_jMEjemplarActionPerformed

    private void jMLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLectorActionPerformed
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        LectorView lv = new LectorView();
        lv.setVisible(true);
        jDEscritorio.add(lv);
        jDEscritorio.moveToFront(lv);
    }//GEN-LAST:event_jMLectorActionPerformed

    private void jMLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLibroActionPerformed
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        LibroView lbv = new LibroView();
        lbv.setVisible(true);
        jDEscritorio.add(lbv);
        jDEscritorio.moveToFront(lbv);
    }//GEN-LAST:event_jMLibroActionPerformed

    private void jMPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPrestamoActionPerformed
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        PrestamoView pv = new PrestamoView();
        pv.setVisible(true);
        jDEscritorio.add(pv);
        jDEscritorio.moveToFront(pv);
    }//GEN-LAST:event_jMPrestamoActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDEscritorio;
    private javax.swing.JMenuItem jMEjemplar;
    private javax.swing.JMenuItem jMLector;
    private javax.swing.JMenuItem jMLibro;
    private javax.swing.JMenuItem jMPrestamo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
